ConnectCodes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('api/',include("api.urls")),
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('room/', include('rooms.urls')),
    path('profile/', include('accounts.urls')),
    path("accounts/", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("room-details/<int:pk>", views.get_room_details),
    # path("user-detail/<int:pk>", views.get_user_details)
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.gethomepage, name='homepage')
]

home/models.py
from django.db import models

# Create your models here.

rooms/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Topic(models.Model):
    topic = models.CharField(max_length = 40)

    def __str__(self):
        return self.topic
    
class SubTopic(models.Model):
    subtopic = models.CharField(max_length = 40)
    main_topic = models.ForeignKey(Topic, on_delete = models.CASCADE)
    def __str__(self):
        return self.subtopic

class Room(models.Model):
    topic = models.ForeignKey(Topic, on_delete = models.CASCADE)
    subtopic = models.ForeignKey(SubTopic, on_delete = models.CASCADE)
    host = models.ForeignKey(User, on_delete = models.CASCADE, related_name="room_host")
    discription = models.TextField()
    members = models.ManyToManyField(User, related_name="room_members")
    
    def __str__(self):
        return self.discription[:20]
    
class Message(models.Model): 
    room = models.ForeignKey('Room', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    message = models.TextField()

    def __str__(self):
        return self.message[:20]

home/views.py
from django.shortcuts import render, redirect, reverse
from rooms.models import Room, Topic
from django.contrib.auth import get_user_model

from django.db.models import Q
from django.views.generic.base import TemplateView

User = get_user_model()

def gethomepage(request):
    search = request.GET.get("search")
    search = "" if search == None else search
    rooms = None

    
    rooms = Room.objects.filter(Q(topic__topic__icontains = search) | 
                                Q(host__username__icontains = search) |
                                Q(discription__icontains = search) |
                                Q(topic__subtopic__subtopic__icontains = search)).order_by("-id")

    
    topics = Topic.objects.all()
    return render(request, 'home/home.html', {"rooms":rooms, "topics":topics})

home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %} - home {% endblock%}
{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/home.css' %}" />
{% endblock %}
{% block content %}
{% include "header_with_search.html" %}
<main>
  <div class="topics_box">
    <img src="{% static 'equipments/website_icons/homepage/arrow.svg' %}" alt="" class="revealer" onclick="revealBox()">
    <h2 class='center'>Topics</h2>
    <ul class="topics">
      {% for topic_name in topics %}
      <li>
        <a href="?search={{ topic_name.topic }}">{{ topic_name.topic }}</a>
      </li>
      {% endfor %}
    </ul>
  </div>
  <div class="main_container">
    <div class="main_container_header">
      <h1>Rooms</h1>
      <a href="{% url 'createroompage' %}" class="create_room_button center">Create New Room</a>
    </div>
    {% for room in rooms %}
    <div class="room_card">
      <div class="room_card_header">
        <a href="{% url 'profilepage' %}?profile={{ room.host.username }}" class="room_host">
          <img src="/media/{{ room.host.profile_pic }}" alt="profile_pic" class="profile_pic">@{{ room.host.username }}
        </a>
        <div class="center topic_name">{{ room.topic.topic}}</div>
        <!-- perms.rooms.delete_room  or  -->
        
        {% if room.host == request.user or perms.rooms.delete_room %}
          <form class="delete_button_form" data-url="{% url 'deleteroom' room.id %}">
          {% csrf_token %}
            <button type="submit" class="center delete_button">Delete</button>
          </form>
        {% endif %}
      </div>
      <p class="room_discription">{{ room.discription }}</p>
      <hr />
      <div class="room_card_footer">
        <p class="room_member_count"><img src="{% static 'equipments/website_icons/homepage/members.svg' %}" alt="members icon" class="members_logo">{{ room.members.all.count }} Members</p>
        <a href="{% url 'roompage' room.id %}" class="see_room_button center">See Room</a>
      </div>
    </div>
    {% endfor %}

    
  </div>
  <div class="friends_box">
    <h2 class="center">Your Follows</h2>
    <ul class="friends_list">
      {% for friend in request.user.following.all %}
      <li class="friend">
        <a href="{% url 'profilepage' %}?profile={{ friend.username }}" class="room_host">
          <img src="media/{{ friend.profile_pic }}" alt="profile_pic" class="profile_pic">@{{ friend.username }}
        </a>
      </li>
      {% endfor %}
    </ul>
  </div>
</main>

<script src="{% static 'js/home_responsive.js' %}"></script>
<script src="{% static 'js/delete_room.js' %}"></script>

{% endblock %}

home/templates/home/profilepage.html
{% extends 'base.html' %}
{% load static %}

{% block title %} -Profile {% endblock %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/profilepage.css' %}" />
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;600&display=swap" rel="stylesheet"/>
{% endblock %}
{% block content %}
{% include 'header.html' %}

<main class="profile-page">
  <div class="content">
    <div class="content__cover">
      <div class="content__avatar">
        <img src="/media/{{user.profile_pic}}" alt="Profile_Pic"></img>
      </div>
      
    </div>
    <div class="content__actions">
      {% if not request.user == user %}
      <form method="post">
        {% csrf_token %}
        <button class="button"
        {% if not request.user.username == user.username %}
        type="submit" name="commit" value="{% if already_following %} unfollow {{user.username}}{% else %}follow {{user.username}}{% endif %}"

        {% endif %}>
          {% if already_following %}
          Unfollow
          {% else %}
          Follow
          {% endif %}
        </button></form>
        {% endif %}
      
      <a href="#" class="button"><span>Message</span></a>
    </div>
    <div class="content__title">
      <h1>{{ user.full_name }}</h1>
      <h3>@{{ user.username }}</h3>
      <span>Kathmandu, Nepal</span>
    </div>
    <div class="content__description">
      <p>Web Producer - Web Specialist</p>
      <p>Columbia University - New York</p>
    </div>
    <ul class="content__list">
      <li><span class="numbers">{{followers}}</span>Followers</li>
      <li><span class="numbers">{{room_count}}</span>Rooms</li>
      <li><span class="numbers">{{following}}</span>Following</li>
    </ul>
    <div class="content__button">
      <a class="button" href="#">
        <div class="button__border"></div>
        <div class="button__bg"></div>
        <p class="button__text">Show more</p></a>
    </div>
  </div>
</div>

{% endblock %}

home/templates/home/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}- Login{% endblock %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/register.css' %}">
{% endblock %}

{% block content %}
<main class="center">
    <div class="register-container">
        {% if messages %}
        <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }} center"{% endif %}>{{ message }}</li>
        {% endfor %}
        </ul>
        {% endif %}
        <h1>Register to ConnetCodes</h1>
        <form action="#" method="post">
            {% csrf_token %}
            <input type="text" name="full_name" placeholder="Full Name" required>
            <input type="text" name="username" placeholder="Username" required>
            <input type="password" name="password" placeholder="Password" required>
            <input type="password" name="repassword" placeholder="Re-enter Password" required>
            <input type="submit" value="Register">
        </form>
        <div class="login-link">
            <span>Already have an account? </span>
            <a href="{% url 'loginpage' %}">Login</a>
        </div>
    </div>
</main>
{% endblock %}